/* Live administrator portal backed by api/index.php and the signed-in PHP session. */
(function () {
  'use strict';
  var api = window.ParkFlowAPI, ui = window.ParkFlowUI;
  if (!api || !ui || !document.body.classList.contains('admin-portal')) return;
  var state = { profile: null, managers: [], locations: [], rules: [], categories: [], escalatedIssues: [], analytics: null, dashboard: null, managerPendingRemoval: null, managerApprovalDecision: null };
  var money = function (value) { return 'BDT ' + Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 }); };
  var esc = function (value) { var e = document.createElement('span'); e.textContent = value == null ? '' : String(value); return e.innerHTML; };
  var initials = function (name) { return String(name || '?').split(/\s+/).map(function (part) { return part[0] || ''; }).join('').slice(0, 2).toUpperCase(); };
  var time = function (value) { return value ? String(value).slice(0, 5) : '—'; };
  var clockTime = function (value) { return value ? String(value).slice(-8, -3) : '—'; };
  var dateTime = function (value) { var date = new Date(String(value).replace(' ', 'T')); return isNaN(date) ? '—' : date.toLocaleString(); };
  var badge = function (value) { var text = String(value || 'unknown').replace(/_/g, ' '); var cls = /active|operational|completed|approved|confirmed/i.test(text) ? 'success' : /pending|waiting|review|paused|overstayed/i.test(text) ? 'warning' : /cancelled|rejected|suspended|closed/i.test(text) ? 'danger' : 'info'; return '<span class="badge badge--' + cls + ' badge--dot">' + esc(text) + '</span>'; };

  function guard() {
    return api.me().then(function (result) {
      if (!result.user || result.user.role !== 'admin') { window.location.href = 'login.html?account=admin'; throw new Error('Sign in required.'); }
      document.querySelectorAll('.admin-name').forEach(function (name) { name.textContent = result.user.full_name; });
      var greeting = document.querySelector('#admin-overview-title');
      if (greeting) greeting.textContent = 'Welcome, ' + String(result.user.full_name).split(/\s+/)[0];
    });
  }
  function setValue(selector, value) { var el = document.querySelector(selector); if (el) el.textContent = value; }
  function renderProfile(data) {
    var profile = data.profile || data;
    state.profile = profile;
    var name = document.getElementById('admin-profile-name'), email = document.getElementById('admin-profile-email'), phone = document.getElementById('admin-profile-phone');
    if (name) name.value = profile.full_name || '';
    if (email) email.value = profile.email || '';
    if (phone) phone.value = profile.phone || '';
    document.querySelectorAll('.admin-name').forEach(function (item) { item.textContent = profile.full_name || ''; });
  }
  function renderDashboard(data) {
    state.dashboard = data;
    var metrics = data.metrics || {};
    document.querySelectorAll('#overview .kpi-card').forEach(function (card) {
      var label = card.querySelector('.kpi-card__value span'); var output = card.querySelector('.kpi-card__value strong');
      if (!label || !output) return; var key = label.textContent.toLowerCase();
      if (key.indexOf('reservation') >= 0) output.textContent = Number(metrics.reservations || 0).toLocaleString();
      else if (key.indexOf('revenue') >= 0) output.textContent = money(metrics.revenue);
      else if (key.indexOf('occupancy') >= 0) output.textContent = metrics.spaces ? Math.round((metrics.occupied_spaces || 0) * 100 / metrics.spaces) + '%' : '0%';
      else if (key.indexOf('space') >= 0) output.textContent = Number(metrics.spaces || 0).toLocaleString();
    });
    var table = document.querySelector('#overview .dashboard-table tbody');
    if (table) table.innerHTML = (data.recent_reservations || []).map(function (row) {
      return '<tr data-reservation-id="' + row.id + '"><td><strong>#' + esc(row.reservation_code) + '</strong></td><td><div class="table-identity"><span class="avatar avatar--sm">' + esc(initials(row.full_name)) + '</span><span class="table-identity__text"><strong>' + esc(row.full_name) + '</strong><small>' + esc(row.registration_number) + '</small></span></div></td><td>' + esc(row.location_name) + '</td><td>' + esc(clockTime(row.starts_at)) + '–' + esc(clockTime(row.ends_at)) + '</td><td><strong>' + money(row.total_amount) + '</strong></td><td>' + badge(row.status) + '</td><td><button class="icon-btn" data-action="reservation-details" type="button" aria-label="View reservation"><svg fill="none" stroke="currentColor" stroke-width="1.8"><use href="#i-eye"></use></svg></button></td></tr>';
    }).join('') || '<tr><td colspan="7">No reservations have been recorded yet.</td></tr>';
  }
  function renderManagers(rows) {
    state.managers = rows;
    var body = document.querySelector('#managers .dashboard-table tbody');
    if (body) body.innerHTML = rows.map(function (row) {
      return '<tr data-manager-id="' + row.id + '"><td><div class="table-identity"><span class="avatar">' + esc(initials(row.full_name)) + '</span><span class="table-identity__text"><strong>' + esc(row.full_name) + '</strong><small>' + esc(row.email) + '</small></span></div></td><td>' + esc(row.locations || 'Unassigned') + '</td><td>' + esc(row.shift_name || '—') + '</td><td><strong>—</strong></td><td>' + badge(row.account_status) + '</td><td><div class="table-actions"><button class="icon-btn" data-action="manager-edit" type="button" aria-label="Edit ' + esc(row.full_name) + '"><svg fill="none" stroke="currentColor" stroke-width="1.8"><use href="#i-edit"></use></svg></button><button class="icon-btn table-delete" data-action="manager-remove" type="button" aria-label="Suspend ' + esc(row.full_name) + '"><svg fill="none" stroke="currentColor" stroke-width="1.8"><use href="#i-trash"></use></svg></button></div></td></tr>';
    }).join('') || '<tr><td colspan="6">No manager accounts found.</td></tr>';
    document.querySelectorAll('.sidebar-nav__link[href="#managers"] .sidebar-nav__count').forEach(function (count) { count.textContent = rows.filter(function (row) { return row.account_status === 'active'; }).length; });
    var pagination = document.querySelector('#managers .table-pagination'); if (pagination) { var summary = pagination.querySelector('span'); if (summary) summary.textContent = 'Showing ' + rows.length + ' of ' + rows.length + ' managers'; var navigation = pagination.querySelector('nav'); if (navigation) navigation.hidden = true; }
    var statusSelect = document.querySelector('.manager-filterbar select'); if (statusSelect) { var currentStatus = statusSelect.value; var statuses = rows.map(function (row) { return row.account_status; }).filter(function (value, index, values) { return values.indexOf(value) === index; }); statusSelect.innerHTML = '<option>All statuses</option>' + statuses.map(function (status) { return '<option value="' + esc(status) + '">' + esc(status.charAt(0).toUpperCase() + status.slice(1)) + '</option>'; }).join(''); statusSelect.value = currentStatus; }
    fillSelects();
  }
  function fillSelects() {
    [['manager-location', 'Select a parking location'], ['edit-manager-location', 'Select a parking location'], ['pricing-rule-location', 'All locations'], ['space-location', 'Select a parking location']].forEach(function (pair) {
      var select = document.getElementById(pair[0]); if (!select) return;
      var current = select.value; select.innerHTML = '<option value="">' + pair[1] + '</option>' + state.locations.map(function (location) { return '<option value="' + location.id + '">' + esc(location.name) + '</option>'; }).join('');
      select.value = current;
    });
    ['new-location-manager', 'edit-location-manager'].forEach(function (id) {
      var manager = document.getElementById(id); if (!manager) return;
      var current = manager.value; manager.innerHTML = '<option value="">Assign later</option>' + state.managers.filter(function (row) { return row.account_status === 'active'; }).map(function (row) { return '<option value="' + row.id + '">' + esc(row.full_name) + '</option>'; }).join(''); manager.value = current;
    });
  }
  function renderLocations(rows) {
    state.locations = rows;
    var grid = document.querySelector('.admin-location-grid');
    if (grid) grid.innerHTML = rows.map(function (row) {
      var total = Number(row.spaces_total || row.total_capacity || 0); var occupied = Number(row.occupied_spaces || 0); var percent = total ? Math.round(occupied * 100 / total) : 0;
      return '<article class="admin-location-card" data-location-id="' + row.id + '"><header><span class="admin-location-card__mark">P</span>' + badge(row.status) + '</header><div><h3>' + esc(row.name) + '</h3><p>' + esc(row.address) + '</p></div><dl><div><dt>Total spaces</dt><dd>' + esc(row.total_capacity) + '</dd></div><div><dt>Occupied</dt><dd>' + occupied + '</dd></div><div><dt>Rate</dt><dd>' + money(row.base_hourly_rate) + '/hr</dd></div></dl><div class="location-capacity"><span><strong>' + percent + '%</strong> occupied</span><div class="progress progress--success"><div class="progress__bar" style="width:' + percent + '%"></div></div></div><footer><span><small>Manager</small> <strong>' + esc(row.managers || 'Unassigned') + '</strong></span><button class="icon-btn" data-action="location-edit" type="button" aria-label="Edit location">✎</button></footer></article>';
    }).join('') || '<p>No parking locations have been created yet.</p>';
    fillSelects();
  }
  function renderApprovals(rows) {
    var table = document.querySelector('.approval-table tbody'); if (!table) return;
    table.innerHTML = rows.map(function (row) {
      return '<tr data-application-id="' + row.id + '"><td><div class="table-identity"><span class="avatar">' + esc(initials(row.full_name)) + '</span><span class="table-identity__text"><strong>' + esc(row.full_name) + '</strong><small>' + esc(row.phone || row.email) + '</small></span></div></td><td><strong>Parking manager</strong><br><small>' + esc(row.locations || 'Unassigned') + '</small></td><td><span class="text-muted">Account application</span></td><td>' + esc(dateTime(row.created_at)) + '</td><td>' + badge(row.account_status) + '</td><td><div class="approval-actions"><button class="btn btn--success btn--sm" data-action="application-approve" type="button">Approve</button><button class="btn btn--secondary btn--sm" data-action="application-reject" type="button">Reject</button></div></td></tr>';
    }).join('') || '<tr><td colspan="6">There are no manager applications awaiting review.</td></tr>';
    var count = document.querySelector('#manager-approvals .section-toolbar__actions .badge, #manager-approvals .badge--warning');
    if (count && !count.closest('tbody')) count.textContent = rows.length + ' awaiting review';
    document.querySelectorAll('.sidebar-nav__link[href="#manager-approvals"] .sidebar-nav__count').forEach(function (item) { item.textContent = rows.length; });
    var notification = document.querySelector('.notification-item[href="#manager-approvals"]');
    if (notification) { var title = notification.querySelector('strong'), detail = notification.querySelector('p'), stamp = notification.querySelector('time'); if (title) title.textContent = rows.length ? rows.length + ' manager application' + (rows.length === 1 ? '' : 's') + ' await approval' : 'No manager applications await approval'; if (detail) detail.textContent = rows.length ? 'Review and approve new manager access.' : 'Your manager approval queue is clear.'; if (stamp) stamp.textContent = 'Live'; notification.classList.toggle('is-unread', rows.length > 0); }
  }
  function renderPricing(rows) {
    state.rules = rows; var list = document.querySelector('.pricing-rule-list'); if (!list) return;
    list.innerHTML = rows.map(function (row) { var adjustment = Number(row.adjustment_value); return '<article class="pricing-rule" data-rule-id="' + row.id + '"><span class="pricing-rule__icon">%</span><div class="pricing-rule__body"><div><h4>' + esc(row.name) + '</h4>' + badge(adjustment >= 0 ? 'Increase ' + adjustment + '%' : 'Discount ' + Math.abs(adjustment) + '%') + '</div><p>' + esc(time(row.start_time)) + '–' + esc(time(row.end_time)) + ' · ' + esc(row.location_name || 'All locations') + '</p><div class="pricing-rule__meta"><span>Adjustment <strong>' + (adjustment >= 0 ? '+' : '') + adjustment + '%</strong></span><span>Status <strong>' + (Number(row.is_active) ? 'Active' : 'Paused') + '</strong></span></div></div><label class="switch"><input data-action="pricing-toggle" type="checkbox"' + (Number(row.is_active) ? ' checked' : '') + '>Active</label></article>'; }).join('') || '<p>No pricing rules configured.</p>';
    var active = rows.filter(function (row) { return Number(row.is_active); }); var count = document.querySelector('#pricing .panel-header .badge'); if (count) count.textContent = active.length + ' active';
    var previewNow = new Date(); updateRatePreview(previewNow); var previewTime = document.getElementById('pricing-preview-time'); if (previewTime) previewTime.value = String(previewNow.getHours()).padStart(2, '0') + ':' + String(previewNow.getMinutes()).padStart(2, '0');
  }
  function updateRatePreview(now) {
    var active = state.rules.filter(function (row) { return Number(row.is_active); }); var minute = now.getHours() * 60 + now.getMinutes(); var toMinute = function (value) { var pieces = String(value || '00:00').slice(0, 5).split(':'); return Number(pieces[0]) * 60 + Number(pieces[1]); }; var rule = active.filter(function (row) { var start = toMinute(row.start_time), end = toMinute(row.end_time); return start <= end ? minute >= start && minute <= end : minute >= start || minute <= end; })[0]; var location = rule && state.locations.filter(function (row) { return String(row.id) === String(rule.location_id); })[0]; if (!location) location = state.locations[0]; var base = Number(location && location.base_hourly_rate || 0); var adjustment = Number(rule && rule.adjustment_value || 0); var rate = base * (1 + adjustment / 100); var clock = document.querySelector('.pricing-clock strong'); if (clock) clock.textContent = now.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); var sub = document.querySelector('.pricing-clock small'); if (sub) sub.textContent = rule ? rule.name + ' is active for this preview.' : 'Base rate applies at this time.'; var heading = document.querySelector('.pricing-preview .panel-header__copy p'); if (heading) heading.textContent = location ? location.name : 'No locations'; var mainRate = document.querySelector('.current-rate strong'); if (mainRate) mainRate.innerHTML = esc(money(rate)) + '<small>/hour</small>'; var baseRate = document.querySelector('.current-rate em'); if (baseRate) baseRate.textContent = 'Base rate ' + money(base); var breakdown = document.querySelectorAll('.rate-breakdown dd'); if (breakdown.length >= 3) { breakdown[0].textContent = (adjustment >= 0 ? '+' : '') + money(base * adjustment / 100); breakdown[1].textContent = money(0); breakdown[2].textContent = money(rate * 2); }
  }
  function renderCategories(rows) {
    state.categories = rows; var grid = document.querySelector('.violation-category-grid'); if (!grid) return;
    grid.innerHTML = rows.map(function (row) { return '<article class="violation-category" data-category-id="' + row.id + '"><header><span class="violation-category__icon">!</span>' + badge(row.default_severity) + '</header><h3>' + esc(row.name) + '</h3><p>' + esc(row.description) + '</p><footer><span>Default penalty <strong>' + money(row.default_penalty) + '</strong></span><button class="icon-btn" data-action="category-edit" type="button" aria-label="Edit category">✎</button></footer></article>'; }).join('') || '<p>No violation categories configured.</p>';
  }
  function renderEscalatedIssues(rows) {
    state.escalatedIssues = rows || []; var body = document.querySelector('.forwarded-issue-table tbody'); if (!body) return;
    body.innerHTML = state.escalatedIssues.map(function (row) { var closed = /resolved|dismissed/.test(row.status); return '<tr data-forwarded-issue-id="' + row.id + '"><td><strong>#' + esc(row.violation_code) + '</strong><br><small>' + esc(dateTime(row.reported_at)) + '</small></td><td>' + esc(row.location_name || 'Location unavailable') + '</td><td><div class="table-identity"><span class="avatar avatar--sm">' + esc(initials(row.driver_name)) + '</span><span class="table-identity__text"><strong>' + esc(row.driver_name || 'Unknown driver') + '</strong><small>' + esc(row.registration_number || 'No vehicle') + '</small></span></div></td><td><strong>' + esc(row.category) + '</strong><br><small>' + esc(row.description) + '</small></td><td>' + esc(row.manager_name || 'Area manager') + '</td><td>' + badge(row.status) + '</td><td>' + (closed ? badge(row.status) : '<button class="btn btn--primary btn--sm" data-action="forwarded-issue-resolve" type="button">Mark resolved</button>') + '</td></tr>'; }).join('') || '<tr><td colspan="7">No manager-forwarded driver reports.</td></tr>';
  }
  function renderNotifications(data) { var items = data.notifications || [], list = document.querySelector('.topbar-popover[aria-label="Notifications"] .notification-list'); if (!list) return; list.innerHTML = items.map(function (item) { return '<a class="notification-item' + (item.read_at ? '' : ' is-unread') + '" data-action="notification-read" data-notification-id="' + item.id + '" data-link="' + esc(item.link || '#overview') + '" href="' + esc(item.link || '#overview') + '"><span class="notification-item__icon">!</span><span class="notification-item__body"><strong>' + esc(item.title) + '</strong><p>' + esc(item.body) + '</p><time>' + esc(dateTime(item.created_at)) + '</time></span>' + (item.read_at ? '' : '<span class="notification-item__unread"></span>') + '</a>'; }).join('') || '<p class="text-muted">No notifications yet.</p>'; document.querySelectorAll('.topbar-icon__dot').forEach(function (dot) { dot.hidden = !data.unread_count; }); }
  function loadNotifications() { return api.request('notifications').then(renderNotifications).catch(function () { /* Notifications do not block administration. */ }); }
  function renderAnalytics(data) {
    state.analytics = data;
    var locations = data.locations || []; var totalRevenue = locations.reduce(function (sum, row) { return sum + Number(row.revenue || 0); }, 0); var totalBookings = locations.reduce(function (sum, row) { return sum + Number(row.reservations || 0); }, 0);
    document.querySelectorAll('#analytics .kpi-card').forEach(function (card) { var label = card.querySelector('.kpi-card__value span'), output = card.querySelector('.kpi-card__value strong'); if (!label || !output) return; var value = label.textContent.toLowerCase(); if (value.indexOf('reservation') >= 0) output.textContent = totalBookings.toLocaleString(); else if (value.indexOf('revenue') >= 0) output.textContent = money(totalRevenue); else if (value.indexOf('performing') >= 0) output.textContent = locations[0] ? locations[0].name : '—'; });
    var list = document.querySelector('.admin-analytics-list');
    if (list) list.innerHTML = locations.map(function (row) { var width = totalRevenue ? Math.round(Number(row.revenue || 0) * 100 / totalRevenue) : 0; return '<div><span><strong>' + esc(row.name) + '</strong><small>' + Number(row.reservations || 0).toLocaleString() + ' reservations</small></span><strong>' + money(row.revenue) + '</strong><div class="progress"><div class="progress__bar" style="width:' + width + '%"></div></div></div>'; }).join('') || '<p>No analytics data for the selected period.</p>';
    var reportRows = document.querySelector('.report-table tbody');
    if (reportRows) reportRows.innerHTML = locations.map(function (row) { var occupancy = Number(row.spaces) ? Math.round(Number(row.occupied || 0) * 100 / Number(row.spaces)) : 0; return '<tr><th scope="row">' + esc(row.name) + '</th><td>' + Number(row.reservations || 0).toLocaleString() + '</td><td>' + occupancy + '%</td><td>' + money(row.revenue) + '</td><td>' + money(0) + '</td><td><strong>' + money(row.revenue) + '</strong></td><td>Current period</td></tr>'; }).join('') || '<tr><td colspan="7">No report data for this period.</td></tr>';
    var foot = document.querySelector('.report-table tfoot'); if (foot) foot.innerHTML = '<tr><th scope="row">Network total</th><td>' + totalBookings.toLocaleString() + '</td><td>—</td><td>' + money(totalRevenue) + '</td><td>' + money(0) + '</td><td>' + money(totalRevenue) + '</td><td>Current period</td></tr>';
    var summary = document.querySelectorAll('.report-summary strong'); if (summary.length >= 4) { summary[0].textContent = money(totalRevenue); summary[1].textContent = money(totalRevenue); summary[2].textContent = totalBookings.toLocaleString(); summary[3].textContent = totalBookings ? money(totalRevenue / totalBookings) : money(0); } var reportHeader = document.querySelector('.report-document__header > div:last-child'); if (reportHeader) { var end = data.period_end ? new Date(data.period_end + 'T00:00:00') : new Date(); var heading = reportHeader.querySelector('strong'), generated = reportHeader.querySelector('small'); if (heading) heading.textContent = end.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }); if (generated) generated.textContent = 'Generated ' + new Date().toLocaleString(); }
  }
  function load() {
    return Promise.all([api.request('admin/profile'), api.request('admin/dashboard'), api.request('admin/managers'), api.request('admin/locations'), api.request('admin/manager-approvals'), api.request('admin/pricing-rules'), api.request('admin/violation-categories'), api.request('admin/forwarded-driver-reports'), api.request('admin/analytics?days=30')]).then(function (data) { renderProfile(data[0]); renderDashboard(data[1]); renderManagers(data[2].managers); renderLocations(data[3].locations); renderApprovals(data[4].applications); renderPricing(data[5].rules); renderCategories(data[6].categories); renderEscalatedIssues(data[7].reports); renderAnalytics(data[8]); var context = document.querySelector('.topbar-context small'); if (context) context.textContent = new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }); });
  }
  function close(id) { ui.closeModal(document.getElementById(id)); }
  function locationChoices() { return state.locations.map(function (row) { return row.id + ': ' + row.name; }).join('\n'); }
  function managerChoices() { return state.managers.filter(function (row) { return row.account_status === 'active'; }).map(function (row) { return row.id + ': ' + row.full_name; }).join('\n'); }
  function refresh(message) { return load().then(function () { if (message) ui.toast(message); }); }

  document.addEventListener('submit', function (event) {
    var form = event.target;
    if (!form.closest('.admin-portal') && !form.closest('.modal')) return;
    if (form.id === 'admin-profile-form') { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); api.request('admin/profile', { method: 'PUT', body: { name: document.getElementById('admin-profile-name').value.trim(), phone: document.getElementById('admin-profile-phone').value.trim() } }).then(function () { return refresh('Profile saved.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.closest('#add-manager')) { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); var name = document.getElementById('manager-first-name').value.trim() + ' ' + document.getElementById('manager-last-name').value.trim(); api.request('admin/managers', { method: 'POST', body: { name: name.trim(), email: document.getElementById('manager-email').value.trim(), phone: document.getElementById('manager-phone').value.trim(), password: document.getElementById('manager-password').value, location_id: document.getElementById('manager-location').value, shift_start: document.getElementById('manager-shift-start').value, shift_end: document.getElementById('manager-shift-end').value } }).then(function () { form.reset(); close('add-manager'); return refresh('Manager application created. Approve it before sign-in.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.id === 'edit-manager-form') { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); var managerId = document.getElementById('edit-manager-id').value; api.request('admin/managers/' + managerId, { method: 'PUT', body: { name: document.getElementById('edit-manager-name').value.trim(), phone: document.getElementById('edit-manager-phone').value.trim(), location_id: document.getElementById('edit-manager-location').value, shift_start: document.getElementById('edit-manager-shift-start').value, shift_end: document.getElementById('edit-manager-shift-end').value } }).then(function () { close('edit-manager'); return refresh('Manager details updated.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.id === 'edit-location-form') { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); var locationId = document.getElementById('edit-location-id').value; api.request('admin/locations/' + locationId, { method: 'PUT', body: { name: document.getElementById('edit-location-name').value.trim(), address: document.getElementById('edit-location-address').value.trim(), area: document.getElementById('edit-location-area').value.trim(), capacity: document.getElementById('edit-location-capacity').value, rate: document.getElementById('edit-location-rate').value, status: document.getElementById('edit-location-status').value, manager_user_id: document.getElementById('edit-location-manager').value || null } }).then(function () { close('edit-location'); return refresh('Parking location updated.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.id === 'add-space-form') { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); api.request('admin/locations/' + document.getElementById('space-location').value + '/spaces', { method: 'POST', body: { space_code: document.getElementById('space-code').value.trim(), space_type: document.getElementById('space-type').value, status: document.getElementById('space-status').value } }).then(function () { form.reset(); close('add-space'); return refresh('Parking space added.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.closest('#add-location')) { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); api.request('admin/locations', { method: 'POST', body: { name: document.getElementById('new-location-name').value.trim(), address: document.getElementById('new-location-address').value.trim(), area: 'Dhaka', capacity: document.getElementById('new-location-capacity').value, rate: document.getElementById('new-location-rate').value, manager_user_id: document.getElementById('new-location-manager').value || null } }).then(function () { form.reset(); close('add-location'); return refresh('Parking location created with its available spaces.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.closest('#add-pricing-rule')) { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); var multiplier = parseFloat(String(document.getElementById('pricing-multiplier').value).replace(/[^\d.]/g, '')) || 1; api.request('admin/pricing-rules', { method: 'POST', body: { name: document.getElementById('pricing-rule-name').value.trim(), location_id: document.getElementById('pricing-rule-location').value || null, start_time: document.getElementById('pricing-start-time').value, end_time: document.getElementById('pricing-end-time').value, adjustment_value: Math.round((multiplier - 1) * 100), is_active: form.querySelector('input[type="checkbox"]').checked } }).then(function () { form.reset(); close('add-pricing-rule'); return refresh('Pricing rule saved.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.id === 'edit-violation-category-form') { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); var categoryId = document.getElementById('edit-violation-category-id').value; api.request('admin/violation-categories/' + categoryId, { method: 'PUT', body: { name: document.getElementById('edit-violation-category-name').value.trim(), description: document.getElementById('edit-violation-category-description').value.trim(), severity: document.getElementById('edit-violation-severity').value, penalty: document.getElementById('edit-violation-penalty').value } }).then(function () { close('edit-violation-category'); return refresh('Violation category updated.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (form.closest('#add-violation-category')) { event.preventDefault(); event.stopImmediatePropagation(); if (!form.checkValidity()) return form.reportValidity(); var severity = { Minor: 'low', Moderate: 'medium', Major: 'high', Critical: 'critical' }[document.getElementById('violation-severity').value] || 'medium'; api.request('admin/violation-categories', { method: 'POST', body: { name: document.getElementById('violation-category-name').value.trim(), description: document.getElementById('violation-category-description').value.trim(), severity: severity, penalty: document.getElementById('violation-penalty').value || 0 } }).then(function () { form.reset(); close('add-violation-category'); return refresh('Violation category saved.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
  }, true);

  document.addEventListener('click', function (event) {
    var button = event.target.closest('[data-action], [data-report-download]'); if (!button) return;
    var action = button.dataset.action;
    if (button.hasAttribute('data-report-download')) { event.preventDefault(); event.stopImmediatePropagation(); var report = state.analytics || { locations: [] }; var lines = (report.locations || []).map(function (row) { return row.name + ': ' + row.reservations + ' reservations, ' + money(row.revenue); }); ui.createPdf('ParkFlow Revenue Report', lines, 'parkflow-revenue-report.pdf'); return; }
    if (!action) return; event.preventDefault(); event.stopImmediatePropagation();
    if (action === 'manager-remove') { openManagerRemoval(button.closest('tr').dataset.managerId); }
    else if (action === 'manager-remove-confirm') { var managerId = state.managerPendingRemoval; if (!managerId) return; api.request('admin/managers/' + managerId, { method: 'DELETE', body: {} }).then(function () { state.managerPendingRemoval = null; close('remove-manager'); return refresh('Manager access suspended.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (action === 'application-approve' || action === 'application-reject') { openManagerApprovalDecision(button.closest('tr').dataset.applicationId, action === 'application-approve' ? 'approve' : 'reject'); }
    else if (action === 'manager-approval-confirm') { var review = state.managerApprovalDecision; if (!review) return; api.request('admin/manager-approvals/' + review.id, { method: 'POST', body: { decision: review.decision } }).then(function () { state.managerApprovalDecision = null; close('manager-approval-decision'); return refresh('Manager application ' + (review.decision === 'approve' ? 'approved.' : 'rejected.')); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (action === 'pricing-toggle') { var rule = state.rules.filter(function (row) { return String(row.id) === button.closest('.pricing-rule').dataset.ruleId; })[0]; if (!rule) return; api.request('admin/pricing-rules/' + rule.id, { method: 'PUT', body: { name: rule.name, location_id: rule.location_id, start_time: time(rule.start_time), end_time: time(rule.end_time), adjustment_value: rule.adjustment_value, is_active: button.checked } }).then(function () { return refresh('Pricing rule updated.'); }).catch(function (error) { button.checked = !button.checked; ui.toast(error.message, 'warning'); }); }
    else if (action === 'reservation-details') { var row = button.closest('tr'); ui.toast('Reservation ' + row.cells[0].textContent.trim() + ': ' + row.cells[1].innerText.replace(/\s+/g, ' ') + ', ' + row.cells[2].textContent.trim() + '.'); }
    else if (action === 'manager-edit') { editManager(button.closest('tr').dataset.managerId); }
    else if (action === 'location-edit') { editLocation(button.closest('.admin-location-card').dataset.locationId); }
    else if (action === 'category-edit') { editCategory(button.closest('.violation-category').dataset.categoryId); }
    else if (action === 'forwarded-issue-resolve') { var caseId = button.closest('tr').dataset.forwardedIssueId; if (!caseId) return; button.disabled = true; api.request('admin/forwarded-driver-reports/' + caseId + '/resolve', { method: 'POST', body: { note: 'Resolved by administrator.' } }).then(function () { return refresh('Forwarded driver report resolved.'); }).catch(function (error) { button.disabled = false; ui.toast(error.message, 'warning'); }); }
    else if (action === 'notifications-read') { api.request('notifications/read', { method: 'POST', body: {} }).then(function () { return loadNotifications(); }).then(function () { ui.toast('Notifications marked as read.'); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
    else if (action === 'notification-read') { var notificationLink = button.dataset.link || '#overview'; api.request('notifications/' + button.dataset.notificationId + '/read', { method: 'POST', body: {} }).then(function () { window.location.hash = notificationLink; return loadNotifications(); }).catch(function (error) { ui.toast(error.message, 'warning'); }); }
  }, true);

  function editManager(id) { var row = state.managers.filter(function (item) { return String(item.id) === String(id); })[0]; if (!row) return; var assigned = state.locations.filter(function (location) { return String(row.locations || '').split(', ').indexOf(location.name) >= 0; })[0]; document.getElementById('edit-manager-id').value = row.id; document.getElementById('edit-manager-name').value = row.full_name || ''; document.getElementById('edit-manager-phone').value = row.phone || ''; document.getElementById('edit-manager-location').value = assigned ? assigned.id : ''; document.getElementById('edit-manager-shift-start').value = String(row.shift_start || '08:00').slice(0, 5); document.getElementById('edit-manager-shift-end').value = String(row.shift_end || '16:00').slice(0, 5); ui.openModal(document.getElementById('edit-manager')); }
  function openManagerRemoval(id) { var row = state.managers.filter(function (item) { return String(item.id) === String(id); })[0]; if (!row) return; state.managerPendingRemoval = row.id; document.querySelectorAll('.remove-manager-name').forEach(function (item) { item.textContent = row.full_name; }); ui.openModal(document.getElementById('remove-manager')); }
  function openManagerApprovalDecision(id, decision) { var row = document.querySelector('[data-application-id="' + id + '"]'); var name = row ? row.querySelector('.table-identity__text strong').textContent : 'this manager'; state.managerApprovalDecision = { id: id, decision: decision }; var approving = decision === 'approve'; document.getElementById('manager-approval-decision-title').textContent = (approving ? 'Approve ' : 'Reject ') + name + '?'; document.querySelector('.manager-approval-decision-copy').textContent = approving ? 'This manager will gain access to their assigned location.' : 'This manager application will be declined.'; document.querySelector('.manager-approval-decision-detail').textContent = approving ? 'You can change the manager assignment later from the Managers section.' : 'The applicant will not be able to sign in with this application.'; var confirm = document.querySelector('[data-action="manager-approval-confirm"]'); confirm.textContent = approving ? 'Approve manager' : 'Reject application'; confirm.classList.toggle('btn--danger', !approving); confirm.classList.toggle('btn--primary', approving); ui.openModal(document.getElementById('manager-approval-decision')); }
  function editLocation(id) { var row = state.locations.filter(function (item) { return String(item.id) === String(id); })[0]; if (!row) return; var manager = state.managers.filter(function (item) { return String(row.managers || '').split(', ').indexOf(item.full_name) >= 0; })[0]; document.getElementById('edit-location-id').value = row.id; document.getElementById('edit-location-name').value = row.name || ''; document.getElementById('edit-location-address').value = row.address || ''; document.getElementById('edit-location-area').value = row.area || ''; document.getElementById('edit-location-capacity').value = row.total_capacity || ''; document.getElementById('edit-location-rate').value = row.base_hourly_rate || ''; document.getElementById('edit-location-status').value = row.status || 'operational'; document.getElementById('edit-location-manager').value = manager ? manager.id : ''; ui.openModal(document.getElementById('edit-location')); }
  function editCategory(id) { var row = state.categories.filter(function (item) { return String(item.id) === String(id); })[0]; if (!row) return; document.getElementById('edit-violation-category-id').value = row.id; document.getElementById('edit-violation-category-name').value = row.name || ''; document.getElementById('edit-violation-category-description').value = row.description || ''; document.getElementById('edit-violation-severity').value = row.default_severity || 'medium'; document.getElementById('edit-violation-penalty').value = row.default_penalty || 0; ui.openModal(document.getElementById('edit-violation-category')); }
  var search = document.getElementById('manager-search'); if (search) search.addEventListener('input', function () { var q = search.value.trim().toLowerCase(); document.querySelectorAll('#managers tbody tr').forEach(function (row) { row.hidden = !!q && row.textContent.toLowerCase().indexOf(q) === -1; }); });
  var managerStatus = document.querySelector('.manager-filterbar select'); if (managerStatus) { var filterManagers = function () { var wanted = managerStatus.value.toLowerCase(); document.querySelectorAll('#managers tbody tr').forEach(function (row) { var status = (row.cells[4] ? row.cells[4].textContent : '').trim().toLowerCase(); row.hidden = wanted !== 'all statuses' && status !== wanted; }); }; managerStatus.addEventListener('change', filterManagers); var filterButton = document.querySelector('.manager-filterbar button'); if (filterButton) filterButton.addEventListener('click', function (event) { event.preventDefault(); event.stopImmediatePropagation(); filterManagers(); }); }
  var globalSearch = document.querySelector('.topbar-search'); if (globalSearch) globalSearch.addEventListener('submit', function (event) { event.preventDefault(); event.stopImmediatePropagation(); var query = (document.getElementById('admin-search').value || '').trim().toLowerCase(); var found = state.managers.concat(state.locations, state.rules, state.categories).filter(function (row) { return JSON.stringify(row).toLowerCase().indexOf(query) >= 0; }); if (!query) return ui.toast('Enter a manager, location, pricing rule, or category to search.', 'warning'); if (!found.length) return ui.toast('No matching live records found.'); ui.toast(found.length + ' matching live record' + (found.length === 1 ? '' : 's') + ' found.'); });
  document.querySelectorAll('#analytics .section-toolbar__actions select').forEach(function (select) { select.addEventListener('change', function () { var days = /7/.test(select.value) ? 7 : /year/i.test(select.value) ? 365 : 30; api.request('admin/analytics?days=' + days).then(renderAnalytics).catch(function (error) { ui.toast(error.message, 'warning'); }); }); });
  document.querySelectorAll('#reports button').forEach(function (button) { if (/print/i.test(button.textContent)) button.addEventListener('click', function (event) { event.preventDefault(); event.stopImmediatePropagation(); window.print(); }, true); });
  var previewForm = document.querySelector('.pricing-preview__controls'); if (previewForm) previewForm.addEventListener('submit', function (event) { event.preventDefault(); event.stopImmediatePropagation(); var value = document.getElementById('pricing-preview-time').value; if (!value) return; var when = new Date(); var parts = value.split(':'); when.setHours(Number(parts[0]), Number(parts[1]), 0, 0); updateRatePreview(when); ui.toast('Rate preview updated.'); }, true);
  document.querySelectorAll('.profile-popover a[href="index.html"]').forEach(function (link) { link.addEventListener('click', function (event) { event.preventDefault(); api.logout().finally(function () { window.location.href = 'index.html'; }); }, true); });
  guard().then(load).then(loadNotifications).catch(function (error) { if (error && error.message !== 'Sign in required.') ui.toast(error.message, 'warning'); });
})();
